08_SeedData/seeddata/movies/urls.py
from django.urls import path
from . import views

app_name = 'movie'

urlpatterns = [
    path('', views.movie_list, name='list'),
    path('<int:movie_id>/detail/', views.movie_detail, name='detail'),
    path('<int:movie_id>/movie_del/', views.movie_delete, name = 'movie_del'),
    path('<int:movie_id>/edit/', views.movie_edit ,name='edit'),
    path('score_new/<int:movie_id>/scores/new/', views.score_new, name = 'score_new'),
    path('score_del/<int:movie_id>/scores/<int:score_id>/delete/', views.score_delete, name = 'score_del'),
]

08_SeedData/seeddata/seeddata/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/',include('movies.urls')),
]

08_SeedData/seeddata/movies/models.py
from django.db import models

class Genre(models.Model):
    name = models.CharField(max_length=20, default='')
    def __str__(self):
        return f'{self.id}: {self.name}'

class Movie(models.Model):
    title = models.CharField(max_length=200)
    audience = models.IntegerField()
    poster_url = models.TextField()
    description = models.TextField()
    genre = models.ForeignKey(Genre, default='', on_delete=models.SET_DEFAULT)

    def __str__(self):
        return f'{self.id}: {self.title} , {self.genre.name}'

class Score(models.Model):
    content = models.CharField(max_length=80, default='')
    score = models.FloatField()
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.id}: {self.movie.title}/ {self.content}/ {self.score}'

08_SeedData/seeddata/movies/forms.py
from django import forms
from .models import Movie, Score

class MovieModelForm(forms.ModelForm):
    class Meta:
        model = Movie  # 사용하고 있는 모델만 알려주면 된다.
        fields = ['title', 'audience', 'poster_url', 'description', 'genre']  # 어떤 필드를 만들지 구체적으로 알려줌
        widgets = {
            'title': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'value': '영화제목을 입력해주세요',
                }),
            'audience': forms.NumberInput(
                attrs={
                    'class': 'form-control',
                }),\
            'poster_url': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': '영화이미지 url을 입력해주세요',
                }),
            # 'genre': forms.select(
            #     attrs={
            #         'class': 'form-control',
            #     }),
            'genre': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': '영화장르를 입력해주세요',
                }),
            'description': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': '영화소개를 작성해 주세요',
                }),
        }

class ScoreModelForm(forms.ModelForm):
    class Meta:
        model = Score  # 사용하고 있는 모델만 알려주면 된다.
        fields = ['content',]  # 어떤 필드를 만들지 구체적으로 알려줌
        widgets = {
            # 'title': forms.TextInput(
            #     # attrs 안에는 attribute(속성)가 들어간다.
            #     attrs={
            #         'class': 'form-control',
            #         'placeholder': '제목을 입력해주세요',
            #     }),
            'content': forms.Textarea(
                attrs={
                    'class': 'form-control',
                    'placeholder': '관람평을 작성해 주세요',
                }),
        }

08_SeedData/seeddata/movies/views.py
from django.shortcuts import render , get_object_or_404, redirect
from .models import Movie, Score
from .forms import MovieModelForm

# 영화목록 GET/movies/
def movie_list(request):
    movies = Movie.objects.all()
    context ={'movies':movies}
    return render(request,'movie/list.html',context)

# 영화정보조회 GET/movies/1/
# 평점목록 GET/movies/1/
def movie_detail(request,movie_id):
    movie = get_object_or_404(Movie,id = movie_id)
    scores = movie.score_set.all()
    context = {'movie':movie, 'scores':scores}
    return render(request,'movie/detail.html',context)

# 영화정보수정
def movie_edit(request,movie_id):
    movie = get_object_or_404(Movie, id= movie_id)
    edit_form = MovieModelForm(request.POST, instance=movie)
    if edit_form.is_valid():
        movie.save()
    return redirect('movie:detail', movie_id)

# 영화정보삭제 POST/movies/1/delete/
def movie_delete(request,movie_id):
    movie = get_object_or_404(Movie, id = movie_id)
    if request.method == 'POST':
        movie.delete()
    return redirect('movie:list')


# 평점생성 POST/movies/1/scores/new/
def score_new(request,movie_id):
    movie = get_object_or_404(Movie, id = movie_id)
    if request.method == 'POST':
        score = Score()
        score.content = request.POST.get('content')
        score.score = request.POST.get('score')
        # if score.score and score.content:
        score.movie = movie
        score.save()
    return redirect('movie:detail',movie_id)


# 평점 삭제 POST/movies/1/scores/1/delete/
def score_delete(request,movie_id,score_id):
    movie = get_object_or_404(Movie, id=movie_id)
    score = get_object_or_404(Score, id=score_id)
    if request.method == 'POST':
        score.delete()

    return redirect('movie:detail',movie_id)

08_SeedData/seeddata/movies/templates/movie/_score.html
<!-- 아래에 모든 한줄평과 평점을 출력합니다.  -->
<!-- 삭제 버튼이 있고, 클릭시 POST 삭제  -->
<div class="container mt-5">
        <table class="table">
            <thead>
                <tr>
                    <th>평점</th>
                    <th>한줄평가</th>
                    <th>-</th>
                </tr>
            </thead>
            <tbody>
            {% if scores %}
                {% for score in scores %}
                <tr>
                    <td>{{ score.score }}</td>
                    <td>{{ score.content }}</td>
                    <td>
                        <form action="{% url 'movie:score_del' movie.id score.id %}" method="POST">
                            <button type="submit" class='btn btn-primary ml-3' onclick="return confirm('정말 삭제?')"
                                    style="width: 60px">삭제
                            </button>
                            {% csrf_token %}
                        </form>
                    </td>
                </tr>
                {% endfor %}
            {% else %}
                <td>-</td>
                <td>No comment yet</td>
                <td>-</td>
            {% endif %}
            </tbody>
        </table>

</div>



<!-- 한줄평과 평점(숫자) 받는 폼  -->
<!-- POST 제출  -->
<form action="{% url 'movie:score_new' movie.id %}" method="POST">
    {% csrf_token %}

                <div class="input-group mb-1 mt-5">
                    <div class="input-group col-3 ml-3">
                        <span class="input-group-text " id="basic-addon2">별점</span>
                        <input type="number" max="10" min="0" step="0.5" class="form-control" value="{{ movie.score }}"
                               name="score"
                               aria-label="Recipient's username" aria-describedby="basic-addon2">
                    </div>
                    <input type="text" name='content' id="content" class="form-control col-8" placeholder="한줄평가를 작성 해주세요">
                    <button type="submit" class="btn btn-primary ml-3">Submit</button>
                </div>


</form>

08_SeedData/seeddata/movies/templates/movie/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- bootstrap CDN -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>
<!-- nav bar -->
<ul class="nav nav-tabs">
    <li class="nav-item">
        <a href="{% url 'movie:list' %}" class="nav-link {% block is_list %}{% endblock %}">BoxOffice</a>
    </li>
    <li class="nav-item">
        <a class="nav-link {% block is_detail %}{% endblock %}">Moive</a>
    </li>
</ul>


<div class="container">

    {% block body %}
    {% endblock %}
</div>



<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>

08_SeedData/seeddata/movies/templates/movie/detail.html
{% extends 'movie/base.html' %}
{% block is_detail %}active{% endblock %}

{% block body %}
<!-- 영화의 모든 정보(장르포함) 표시 -->
<h1>{{movie.title}}</h1>

<p>
    관객수 : {{movie.audience}} <br>
    {{movie.genre}}<br>
    <img src="{{ movie.poster_url }}" class="card-img-top image-fluid" style="width: 400px; height: auto;">
</p>

<p>{{movie.description}}</p>

<!-- 영화정보 최하단에 목록, 수정, 삭제 -->

<a class="btn btn-secondary" href="{% url 'movie:edit' movie.id %}" role="button">수정</a>
<a class="btn btn-secondary" href="{% url 'movie:movie_del' movie.id %}" role="button">삭제</a>
<a class="btn btn-secondary" href="{% url 'movie:list' %}" role="button">목록</a>

<!-- 아래에 모든 한줄평과 평점을 출력합니다.  -->
<!-- score form html 불러오기   -->
{% include 'movie/_score.html' %}

{% endblock %}

08_SeedData/seeddata/movies/templates/movie/list.html
{% extends 'movie/base.html' %}
{% block is_list %}active{% endblock %}

<!-- 모든 영화 목록  표시 -->
<!-- 각 영화의 title, poster -->
<!-- title 클릭시 해당영화 detail 페이지로 -->

{% block body %}
    <section class="card-columns">
        {% for movie in movies %}
            <article class="card mb-3">
                    <img src="{{ movie.poster_url }}" class="card-img-top image-fluid">
                <div class="card-body">
                    <a href="{% url 'movie:detail' movie.id %}">
                        <h4>{{ movie.title }}</h4>
                    </a>
                </div>
            </article>
        {% endfor %}
    </section>
{% endblock %}